"""cls-trainer command line interface.

Workflows:

    cls-trainer train --config configs/npu_1p.yaml [key=value ...]
    cls-trainer train --config ... --dry-run
    cls-trainer train --resume <run_dir>
    cls-trainer config show --config ... [--with-source]
    cls-trainer config validate --config ...
    cls-trainer config reference
    cls-trainer run list [--root runs]
    cls-trainer run show latest|<run_dir>
    cls-trainer doctor --config ...

Every ``train`` start defaults to ``--run-mode unique``: the configured
``experiment.output_dir`` is treated as a runs root and a fresh timestamped
run directory is allocated, so re-running a command can never overwrite a
previous run. ``--run-mode fixed`` restores the legacy in-place behavior.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

RECIPE_TEMPLATE = """\
# Recipe generated by: cls-trainer init --profile {profile}
# Fill the REPLACE_ME fields, then:
#
#   cls-trainer doctor --config {output}
#   cls-trainer train  --config {output} --dry-run
#
# Business facts (threshold 0.99, delta=2 test pairs, cls-only training,
# 448x208 frames) come from the task profile and are intentionally absent here.
# Device/DataLoader stability rules come from the profile.
profile: {profile}

presets:
  augmentation: standard
  dataloader: stable
  evaluation: production

experiment:
  name: {name}
  seed: 20260728
  output_dir: runs/{name}

model:
  factory: REPLACE_ME_PACKAGE.module:build_model
  checkpoint_path: REPLACE_ME/path/to/base_model.pt

data:
  synthetic: false
  require_content_hash_audit: true
  require_unique_video_keys_across_splits: true
  require_independent_test: true
  audit_path: indexes/audit.json
  train_video_index: indexes/train_video_entries.parquet
  val_video_index: indexes/val_video_entries.parquet
  test_video_index: indexes/test_video_entries.parquet
  train_index: indexes/train_frames.parquet
  val_index: indexes/val_frames.parquet
  test_index: indexes/test_frames.parquet
  backend: png
  duplicate_policy:
    same_label_cross_split: error
    same_label_within_split: warning
    cross_label_same_content: error
    same_basename: info

pair:
  train_delta_probability: {{1: 0.15, 2: 0.70, 3: 0.15}}

sampler:
  game_alpha: 0.25
  class_probability: {{0: 0.5, 1: 0.5}}
  deduplicate_within_global_batch: true

optimizer:
  learning_rate: 0.001
  weight_decay: 0.0001

scheduler:
  warmup_steps: 500
  min_learning_rate: 0.00001

train:
  epochs: 10
  steps_per_epoch: 1000
  max_steps: null
  stop_after_steps: null
  resume_path: null
  verify_frozen_parameters: false
  local_batch_size: 64
  gradient_clip_norm: 5.0
  log_every_steps: 50

checkpoint:
  save_last_every_steps: 1000
  save_best_selection: true
  save_best_val_loss: true
  save_best_worst_game: true

# Early stopping watches full validation only; max_steps is a safety cap.
early_stopping:
  enabled: true
  monitor: selection_score
  mode: max
  full_validation_only: true
  burn_in_steps: 6000
  patience_evaluations: 3
  min_delta: 0.001
  restore_best: true
"""


def cmd_init(args: argparse.Namespace) -> int:
    from game_cls.config import list_available_layers

    layers = list_available_layers()
    if args.profile not in layers["profiles"]:
        print(
            f"Unknown profile '{args.profile}'. Available profiles: "
            f"{', '.join(layers['profiles']) or '(none found under configs/profiles/)'}",
            file=sys.stderr,
        )
        return 2
    output = Path(args.output)
    if output.exists() and not args.force:
        print(
            f"{output} already exists; pass --force to overwrite.",
            file=sys.stderr,
        )
        return 2
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        RECIPE_TEMPLATE.format(
            profile=args.profile, name=args.name, output=str(output)
        ),
        encoding="utf-8",
    )
    print(f"Recipe written to {output}")
    print("Next steps:")
    print(f"  1. Replace the REPLACE_ME fields in {output}")
    print(f"  2. cls-trainer doctor --config {output}")
    print(f"  3. cls-trainer train  --config {output} --dry-run")
    return 0
