from __future__ import annotations

from typing import Any, Protocol


class AcceleratorAdapter(Protocol):
    """Wraps accelerator-specific setup and the autocast/grad-scaler facade."""

    @property
    def device(self) -> Any: ...

    @property
    def requires_spawn_workers(self) -> bool: ...

    def setup(self, local_rank: int) -> None: ...

    def autocast(self, enabled: bool, dtype: str): ...

    def synchronize(self) -> None: ...

    def make_grad_scaler(self, enabled: bool, dtype: str) -> Any: ...


class DistributedAdapter(Protocol):
    """Wraps process-group lifecycle and the collective facade."""

    @property
    def rank(self) -> int: ...

    @property
    def world_size(self) -> int: ...

    @property
    def local_rank(self) -> int: ...

    def setup(self, backend: str) -> None: ...

    def wrap_model(self, model: Any, device: Any) -> Any: ...

    def barrier(self) -> None: ...

    def all_reduce(self, tensor: Any, op: str = "sum") -> Any: ...

    def gather_object(self, value: Any, dst: int = 0) -> Any: ...

    def cleanup(self) -> None: ...


class RuntimeStrategy(Protocol):
    """Composition of an accelerator and a distributed adapter.

    The trainer talks to this facade and never branches on accelerator name or
    distributed backend directly.
    """

    @property
    def accelerator(self) -> AcceleratorAdapter: ...

    @property
    def distributed(self) -> DistributedAdapter: ...

    def setup(self) -> None: ...

    def wrap_model(self, model: Any) -> Any: ...

    def backward(self, loss: Any, scaler: Any) -> None: ...

    def clip_gradients(self, parameters: Any, max_norm: float) -> Any: ...

    def optimizer_step(self, optimizer: Any, scaler: Any) -> None: ...

    def autocast(self, enabled: bool, dtype: str): ...

    def barrier(self) -> None: ...

    def synchronize(self) -> None: ...

    def cleanup(self) -> None: ...
